{{- if .Values.pgadmin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.pgadmin.service.port }}
      targetPort: 80
  selector:
    app: pgadmin
{{- end }}
