spring:
  flyway:
    locations: classpath:db/migration,classpath:db/seed
  
  # MongoDB configuration
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/socialdb}
      username: ${SPRING_DATA_MONGODB_USERNAME:admin}
      password: ${SPRING_DATA_MONGODB_PASSWORD:mongopass}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
    
    # Redis configuration
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  
  # Elasticsearch configuration
  elasticsearch:
    uris: ${SPRING_ELASTICSEARCH_URIS:http://127.0.0.1:9200}
    username: ${SPRING_ELASTICSEARCH_USERNAME:}
    password: ${SPRING_ELASTICSEARCH_PASSWORD:}
  
  # Kafka configuration
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: social-media-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

